version: '3.8'
services: 
  mongo-db:
    image: mongo
    restart: always 
    # environment: 
    #   - MONGO_INITDB_ROOT_USERNAME=my-username
    #   - MONGO_INITDB_ROOT_PASSWORD=my-root-password
    volumes: 
      - my_data:/data/db 
  node-web:
    build: 
      context: ./
      dockerfile: Dockerfile
    depends_on: 
      - mongo-db
    volumes: 
      - /app/node_modules
      - ./src:/app 
    ports: 
      - "3000:3000"
  
volumes: 
  my_data: